opt_in_rules: # some rules are turned off by default, so you need to opt-in
 - empty_collection_literal
 - empty_string
 - explicit_init
 - unneeded_parentheses_in_closure_argument
 - operator_usage_whitespace

line_length:
  warning: 1000
  error: 5000

function_body_length:
   warning: 400

type_body_length:
  warning: 2000
  error: 2500

file_length:
  warning: 2000
  error: 2500
  ignore_comment_only_lines: true

identifier_name:
  min_length: 0
  max_length: 100

disabled_rules:  
  - unused_setter_value
  - large_tuple
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - for_where
  - cyclomatic_complexity
  - nesting
  - shorthand_operator
  - type_name
  - void_function_in_ternary
  - switch_case_alignment
  - unavailable_condition
excluded:
  - Carthage
  - Pods
  - Tests
  - Brand/NCBrand.swift
  - iOSClient/NCGlobal.swift
  - iOSClient/Utility/NCLivePhoto.swift
  - DerivedData
  
reporter: "xcode"
