opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - file_types_order
  - unneeded_parentheses_in_closure_argument

# FIX
force_cast: warning
force_try: warning
empty_count:
  severity: warning

type_name:
# validates_start_with_lowercase: true
  validates_start_with_lowercase: false
  
cyclomatic_complexity:
  # error: 20
  error: 75

file_length:
  # error: 1000
  error: 2000

line_length:
  # error: 200
  error: 400
  # warning: 120
  warning: 200

function_parameter_count:
  warning: 5
  # error: 8
  error: 12
  ignores_default_parameters: true

function_body_length:
  # error: 100
  error: 250
  
type_body_length:
  # error: 350
  error: 1000

identifier_name:
  min_length:
      error: 1
      warning: 2
  max_length:
    warning: 40
    error: 60
  # allowed_symbols: []
  allowed_symbols: ["_"]


excluded:
- Carthage
- Pods

reporter: "xcode"