opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - file_types_order
  - unneeded_parentheses_in_closure_argument

# FIX
force_cast: warning
force_try: warning


file_length:
  error: 2000
  # error: 1000

line_length:
  error: 300
  # error: 200

function_parameter_count:
  warning: 5
  error: 8
  ignores_default_parameters: true

identifier_name:
  min_length:
      error: 1
      warning: 2
  max_length:
    warning: 40
    error: 60
  # allowed_symbols: []
  allowed_symbols: ["_"]


excluded:
- Carthage
- Pods

reporter: "xcode"