fastlane_version "2.129.0"

default_platform :ios

platform :ios do


  # Dependencies ***********************

  desc "Resolve External Dependencies (the shell script makes Bitrise work)"
  lane :resolve_dependencies do
    sh("cd .. && xcodebuild -showBuildSettings -project Sheeeeeeeeet.xcodeproj -scheme Sheeeeeeeeet")
    spm(command: "resolve")
  end


  # Test =======================
  
  desc "Run unit tests"
  lane :test do
    swiftlint(strict: true)
    resolve_dependencies
    run_tests(scheme: "Sheeeeeeeeet")
  end


  # Version ================

  desc "Create a new version"
  lane :version do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    test

    bump_type = options[:type]
    if bump_type == nil or bump_type.empty?
      bump_type = "patch"
    end
    
    version = version_bump_podspec(path: "Sheeeeeeeeet.podspec", bump_type: bump_type)
    increment_version_number(version_number: version)

    git_commit(
      path: "*",
      message: "Bump to #{version}"
    )

    add_git_tag(tag: version)
    push_git_tags()
    push_to_git_remote()
    pod_push()
  end
end