fastlane_version "2.129.0"

default_platform :ios

platform :ios do


  # Test =======================
  
  desc "Run unit tests"
  lane :test do
    spm(command: "test")
  end


  # Version ================

  desc "Create a new version"
  lane :version do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    # test        TODO: This doesn't work since SPM can't find UIKit in terminal
    version = version_bump_podspec(path: "Sheeeeeeeeet.podspec", version_number: options[:name])
    increment_version_number(version_number: version)

    git_commit(
      path: [
        "Sheeeeeeeeet.podspec",
        "Fastlane/"
      ],
      message: "Bump to #{version}"
    )

    add_git_tag(tag: version)
    push_git_tags()
    push_to_git_remote()
    pod_push()
  end
  
end
