fastlane_version "2.30.2"

default_platform :ios

platform :ios do


  # Version ================

  desc "Create a new version"
  lane :version do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    test
    version = version_bump_podspec(path: "Sheeeeeeeeet.podspec", version_number: options[:name])
    increment_version_number(version_number: version)

    git_commit(
      path: [
        "Sheeeeeeeeet.podspec",
        "*/Info.plist",
        "*/*.pbxproj",
        "Fastlane/"],
      message: "Bump to #{version}"
    )

    add_git_tag(tag: version)
    push_git_tags()
    push_to_git_remote()
#pod_push()
  end

  
  # Test =======================

  desc "Run unit tests"
  lane :test do
    scan(
      project: "Sheeeeeeeeet.xcodeproj",
      scheme: "Sheeeeeeeeet"
    )    
  end
end
