// SPDX-FileCopyrightText: Nextcloud GmbH
// SPDX-FileCopyrightText: 2018 Marino Faggiana
// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation
import UIKit
import NextcloudKit
import RealmSwift

protocol NCListCellDelegate: AnyObject {
    func onMenuIntent(with metadata: tableMetadata?)
    func openContextMenu(with metadata: tableMetadata?, button: UIButton, sender: Any)
    func tapShareListItem(with metadata: tableMetadata?, button: UIButton, sender: Any)
}

class NCListCell: UICollectionViewCell, UIGestureRecognizerDelegate, NCCellMainProtocol {
    @IBOutlet weak var imageItem: UIImageView!
    @IBOutlet weak var imageSelect: UIImageView!
    @IBOutlet weak var imageStatus: UIImageView!
    @IBOutlet weak var imageFavorite: UIImageView!
    @IBOutlet weak var imageLocal: UIImageView!

    @IBOutlet weak var labelTitle: UILabel!
    @IBOutlet weak var labelInfo: UILabel!
    @IBOutlet weak var labelSubinfo: UILabel!
    @IBOutlet weak var labelInfoSeparator: UILabel!
    @IBOutlet weak var tag0: UILabel!
    @IBOutlet weak var tag1: UILabel!
    @IBOutlet weak var labelExtension: UILabel!

    @IBOutlet weak var buttonShared: UIButton!
    @IBOutlet weak var buttonMore: UIButton!
    @IBOutlet weak var shareContainer: UIView!
    @IBOutlet weak var moreContainer: UIView!
    @IBOutlet weak var separator: UIView!

    @IBOutlet weak var imageItemLeftConstraint: NSLayoutConstraint!
    @IBOutlet weak var separatorHeightConstraint: NSLayoutConstraint!

    weak var delegate: NCListCellDelegate?

    // Cell Protocol
    var metadata: tableMetadata? {
        didSet {
            delegate?.openContextMenu(with: metadata, button: buttonMore, sender: self) /* preconfigure UIMenu with each metadata */
        }
    }
    var previewImg: UIImageView? {
        get { return imageItem }
        set { imageItem = newValue }
    }
    var localImg: UIImageView? {
        get { return imageLocal }
        set { imageLocal = newValue }
    }
    var statusImg: UIImageView? {
        get { return imageStatus }
        set { imageStatus = newValue }
    }
    var infoLbl: UILabel? {
        get { return labelInfo }
        set { labelInfo = newValue }
    }

    override var accessibilityIdentifier: String? {
        get {
            super.accessibilityIdentifier
        }
        set {
            super.accessibilityIdentifier = newValue

            if let newValue {
                buttonShared.accessibilityIdentifier = "\(newValue)/shareButton"
            }
        }
    }

    override func awakeFromNib() {
        super.awakeFromNib()

        let tapObserver = UITapGestureRecognizer(target: self, action: #selector(handleTapObserver(_:)))
        tapObserver.cancelsTouchesInView = false
        tapObserver.delegate = self
        contentView.addGestureRecognizer(tapObserver)

        initCell()
    }

    override func prepareForReuse() {
        super.prepareForReuse()

        initCell()
    }

    func initCell() {
        accessibilityHint = nil
        accessibilityLabel = nil
        accessibilityValue = nil
        isAccessibilityElement = true

        imageItem.image = nil
        imageItem.layer.cornerRadius = 6
        imageItem.layer.masksToBounds = true
        imageStatus.image = nil
        imageFavorite.image = nil
        imageLocal.image = nil
        imageSelect.image = nil

        labelTitle.text = ""
        labelExtension.text = ""
        labelExtension.isHidden = true
        labelInfo.text = ""
        labelSubinfo.text = ""
        tag0.text = ""
        tag1.text = ""

        // Dynamic Type Font Configuration
        //
        // These labels use fonts generated by the custom UIFont helpers defined in
        // the UIFont extension (e.g. `.callout()`, `.caption1()`).
        //
        // Those helpers wrap `UIFontMetrics` to provide Dynamic Type scaling while
        // applying an upper bound to the maximum font size. This ensures:
        //
        // - The text respects the user's preferred accessibility size.
        // - The UI layout remains stable and does not grow indefinitely.
        //
        // `adjustsFontForContentSizeCategory` is enabled to allow UIKit to
        // automatically update the font when the user changes the Dynamic Type
        // setting while the application is running.
        //
        // Without this flag, the label would keep the initially computed font size
        // and would not react to content size category changes.
        //
        // In summary:
        //
        // UIFont helper:
        //     Defines how the font scales and its maximum size.
        //
        // adjustsFontForContentSizeCategory:
        //     Enables live updates when accessibility settings change.
        //
        labelTitle.font = .callout()
        labelTitle.adjustsFontForContentSizeCategory = true

        labelExtension.font = .callout()
        labelExtension.adjustsFontForContentSizeCategory = true

        labelInfo.font = .footnote()
        labelInfo.adjustsFontForContentSizeCategory = true

        labelInfoSeparator.font = .footnote()
        labelInfoSeparator.adjustsFontForContentSizeCategory = true

        labelSubinfo.font = .footnote()
        labelSubinfo.adjustsFontForContentSizeCategory = true

        buttonShared.setImage(nil, for: .normal)
        buttonShared.imageEdgeInsets = .zero

        buttonMore.setImage(nil, for: .normal)
        buttonMore.menu = nil
        buttonMore.showsMenuAsPrimaryAction = true

        shareContainer.isHidden = false
        moreContainer.isHidden = false

        imageItemLeftConstraint.constant = 10
        separatorHeightConstraint.constant = 0.5
    }

    func setSharedAvatarImage(_ image: UIImage) {
        buttonShared.setImage(image, for: .normal)
        buttonShared.imageEdgeInsets = UIEdgeInsets(top: 4, left: 4, bottom: 4, right: 4)
    }

    override func snapshotView(afterScreenUpdates afterUpdates: Bool) -> UIView? {
        return nil
    }

    @IBAction func touchUpInsideShare(_ sender: Any) {
        delegate?.tapShareListItem(with: metadata, button: buttonShared, sender: sender)
    }

    @objc private func handleTapObserver(_ g: UITapGestureRecognizer) {
        let locationInButton = g.location(in: buttonMore)

        if buttonMore.bounds.contains(locationInButton) {
            delegate?.onMenuIntent(with: metadata)
        }
    }

    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        let locationInButton = touch.location(in: buttonMore)
        let result = buttonMore.bounds.contains(locationInButton)

        return result
    }

    func setButtonMore(image: UIImage) {
        buttonMore.setImage(image, for: .normal)
    }

    func hideButtonShare(_ status: Bool) {
        buttonShared.isHidden = status
        shareContainer.isHidden = status
    }

    func setButtonsHidden(_ hidden: Bool) {
        buttonShared.isHidden = hidden
        buttonMore.isHidden = hidden
        shareContainer.isHidden = hidden
        moreContainer.isHidden = hidden
    }

    func selected(_ status: Bool, isEditMode: Bool) {
        if isEditMode {
            imageItemLeftConstraint.constant = 45
            imageSelect.isHidden = false
            buttonShared.isHidden = true
            buttonMore.isHidden = true
            shareContainer.isHidden = true
            moreContainer.isHidden = true
            accessibilityCustomActions = nil
        } else {
            imageItemLeftConstraint.constant = 10
            imageSelect.isHidden = true
            buttonShared.isHidden = false
            buttonMore.isHidden = false
            shareContainer.isHidden = false
            moreContainer.isHidden = false
            backgroundView = nil
        }
        if status {
            var blurEffectView: UIView?
            blurEffectView = UIVisualEffectView(effect: UIBlurEffect(style: .systemMaterial))
            blurEffectView?.backgroundColor = .lightGray
            blurEffectView?.frame = self.bounds
            blurEffectView?.autoresizingMask = [.flexibleWidth, .flexibleHeight]
            imageSelect.image = NCImageCache.shared.getImageCheckedYes()
            backgroundView = blurEffectView
            separator.isHidden = true
        } else {
            imageSelect.image = NCImageCache.shared.getImageCheckedNo()
            backgroundView = nil
            separator.isHidden = false
        }

    }

    func writeInfoDateSize(date: NSDate, size: Int64) {
        labelInfo.text = NCUtility().getRelativeDateTitle(date as Date)
        labelSubinfo.text = NCUtilityFileSystem().transformedSize(size)
    }

    func setAccessibility(label: String, value: String) {
        accessibilityLabel = label
        accessibilityValue = value
    }

    func setTags(tags: [String]) {
        if tags.isEmpty {
            tag0.isHidden = true
            tag1.isHidden = true
            labelInfo.isHidden = false
            labelSubinfo.isHidden = false
            labelInfoSeparator.isHidden = false
        } else {
            tag0.isHidden = false
            tag1.isHidden = true
            labelInfo.isHidden = true
            labelSubinfo.isHidden = true
            labelInfoSeparator.isHidden = true

            if let tag = tags.first {
                tag0.text = tag
                if tags.count > 1 {
                    tag1.isHidden = false
                    tag1.text = "+\(tags.count - 1)"
                }
            }
        }
    }

    func setIconOutlines() {
        [imageStatus, imageLocal].forEach { imageView in
            imageView.makeCircularBackground(withColor: imageView.image != nil ? .systemBackground : .clear)
        }

        if imageFavorite.image != nil {
            let outlineView = UIImageView()
            outlineView.translatesAutoresizingMaskIntoConstraints = false
            outlineView.image = UIImage(systemName: "star")
            outlineView.preferredSymbolConfiguration = UIImage.SymbolConfiguration(pointSize: 16, weight: .thin)
            outlineView.tintColor = .systemBackground

            imageFavorite.addSubview(outlineView)
            NSLayoutConstraint.activate([
                outlineView.leadingAnchor.constraint(equalTo: imageFavorite.leadingAnchor, constant: -1),
                outlineView.trailingAnchor.constraint(equalTo: imageFavorite.trailingAnchor, constant: 1),
                outlineView.topAnchor.constraint(equalTo: imageFavorite.topAnchor, constant: -1),
                outlineView.bottomAnchor.constraint(equalTo: imageFavorite.bottomAnchor, constant: 1)
            ])
            imageFavorite.sendSubviewToBack(outlineView)
        } else {
            imageFavorite.subviews.forEach { view in
                view.removeFromSuperview()
            }
        }
    }

    override func layoutSubviews() {
        super.layoutSubviews()
        // Keep the shadow path in sync with current bounds
        imageStatus.layer.shadowPath = UIBezierPath(ovalIn: imageStatus.bounds).cgPath

        // Ensure the circular background remains correct after Auto Layout
        if imageStatus.layer.cornerRadius != imageStatus.bounds.width / 2 {
            imageStatus.layer.cornerRadius = imageStatus.bounds.width / 2
        }
    }
}

// MARK: - List Layout

class NCListLayout: UICollectionViewFlowLayout {
    var itemHeight: CGFloat = 60

    override init() {
        super.init()

        sectionHeadersPinToVisibleBounds = false

        minimumInteritemSpacing = 0
        minimumLineSpacing = 1

        self.scrollDirection = .vertical
        self.sectionInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override var itemSize: CGSize {
        get {
            if let collectionView = collectionView {
                let itemWidth: CGFloat = collectionView.frame.width
                return CGSize(width: itemWidth, height: self.itemHeight)
            }
            return CGSize(width: 100, height: 100)
        }
        set {
            super.itemSize = newValue
        }
    }

    override func targetContentOffset(forProposedContentOffset proposedContentOffset: CGPoint) -> CGPoint {
        return proposedContentOffset
    }
}

#if !EXTENSION
extension NCCollectionViewCommon {
    func listCell(cell: NCListCell, indexPath: IndexPath, metadata: tableMetadata) -> NCListCell {
        defer {
            let capabilities = NCNetworking.shared.capabilities[session.account] ?? NKCapabilities.Capabilities()
            if !metadata.isSharable() || (!capabilities.fileSharingApiEnabled && !capabilities.filesComments && capabilities.activity.isEmpty) {
                cell.hideButtonShare(true)
            }
        }
        var isShare = false
        var isMounted = false
        var a11yValues: [String] = []
        let existsImagePreview = utilityFileSystem.fileProviderStorageImageExists(metadata.ocId, etag: metadata.etag, userId: metadata.userId, urlBase: metadata.urlBase)

        // CONTENT MODE
        cell.previewImg?.layer.borderWidth = 0

        if existsImagePreview && layoutForView?.layout != global.layoutPhotoRatio {
            cell.previewImg?.contentMode = .scaleAspectFill
        } else {
            cell.previewImg?.contentMode = .scaleAspectFit
        }

        guard let metadata = self.dataSource.getMetadata(indexPath: indexPath) else {
            return cell
        }

        if let metadataFolder {
            isShare = metadata.permissions.contains(NCMetadataPermissions.permissionShared) && !metadataFolder.permissions.contains(NCMetadataPermissions.permissionShared)
            isMounted = metadata.permissions.contains(NCMetadataPermissions.permissionMounted) && !metadataFolder.permissions.contains(NCMetadataPermissions.permissionMounted)
        }

        if isSearchingMode {
            if metadata.name == global.appName {
                cell.labelInfo?.text = NSLocalizedString("_in_", comment: "") + " " + utilityFileSystem.getPath(path: metadata.path, user: metadata.user)
            } else {
                cell.labelInfo?.text = metadata.subline
            }
            cell.labelSubinfo?.isHidden = true
        } else if !metadata.sessionError.isEmpty, metadata.status != global.metadataStatusNormal {
            cell.labelSubinfo?.isHidden = false
            cell.labelInfo?.text = metadata.sessionError
        } else {
            cell.labelSubinfo?.isHidden = false
            cell.writeInfoDateSize(date: metadata.date, size: metadata.size)
        }

        cell.setBidiSafeFilename(metadata.fileNameView, isDirectory: metadata.directory, titleLabel: cell.labelTitle, extensionLabel: cell.labelExtension)

        // Accessibility [shared] if metadata.ownerId != appDelegate.userId, appDelegate.account == metadata.account {
        if metadata.ownerId != metadata.userId {
            a11yValues.append(NSLocalizedString("_shared_with_you_by_", comment: "") + " " + metadata.ownerDisplayName)
        }

        if metadata.directory {
            cellMainDirectory(cell: cell, metadata: metadata, isShare: isShare, isMounted: isMounted)
        } else {
            cellMainFile(cell: cell, metadata: metadata, a11yValues: &a11yValues)
        }

        // image Favorite
        if metadata.favorite {
            cell.imageFavorite?.image = imageCache.getImageFavorite()
            a11yValues.append(NSLocalizedString("_favorite_short_", comment: ""))
        }

        // Share button image (SF Symbol)
        if isShare {
            cell.buttonShared.setImage(imageCache.getImageShared(), for: .normal)
        } else if !metadata.shareType.isEmpty {
            metadata.shareType.contains(NKShare.ShareType.publicLink.rawValue) ?
            (cell.buttonShared.setImage(imageCache.getImageShareByLink(), for: .normal)) :
            (cell.buttonShared.setImage(imageCache.getImageShared(), for: .normal))
        } else {
            cell.buttonShared.setImage(imageCache.getImageCanShare(), for: .normal)
        }

        // Button More
        if metadata.lock == true {
            cell.setButtonMore(image: imageCache.getImageButtonMoreLock())
            a11yValues.append(String(format: NSLocalizedString("_locked_by_", comment: ""), metadata.lockOwnerDisplayName))
        } else {
            cell.setButtonMore(image: imageCache.getImageButtonMore())
        }

        // Status
        cellMainStatus(cell: cell, metadata: metadata, a11yValues: &a11yValues)

        // AVATAR
        if !metadata.ownerId.isEmpty, metadata.ownerId != metadata.userId {
            let fileName = NCSession.shared.getFileName(urlBase: metadata.urlBase, user: metadata.ownerId)
            if let image = NCImageCache.shared.getImageCache(key: fileName) {
                cell.setSharedAvatarImage(image)
            } else {
                self.database.getImageAvatarLoaded(fileName: fileName) { image, tblAvatar in
                    if let image {
                        cell.setSharedAvatarImage(image)
                        NCImageCache.shared.addImageCache(image: image, key: fileName)
                    } else {
                        let image = self.utility.loadUserImage(for: metadata.ownerId, displayName: metadata.ownerDisplayName, urlBase: metadata.urlBase)
                        cell.setSharedAvatarImage(image)
                    }

                    if !(tblAvatar?.loaded ?? false),
                       self.networking.downloadAvatarQueue.operations.filter({ ($0 as? NCOperationDownloadAvatar)?.fileName == fileName }).isEmpty {
                        self.networking.downloadAvatarQueue.addOperation(NCOperationDownloadAvatar(user: metadata.ownerId, fileName: fileName, account: metadata.account, view: self.collectionView))
                    }
                }
            }
        }

        // URL
        if metadata.classFile == NKTypeClassFile.url.rawValue {
            cell.imageLocal.image = nil
            cell.setButtonsHidden(true)
        }

        // Separator
        if collectionView.numberOfItems(inSection: indexPath.section) == indexPath.row + 1 || isSearchingMode {
            cell.separator?.isHidden = true
        } else {
            cell.separator?.isHidden = false
        }

        // Edit mode
        if fileSelect.contains(metadata.ocId) {
            cell.selected(true, isEditMode: isEditMode)
            a11yValues.append(NSLocalizedString("_selected_", comment: ""))
        } else {
            cell.selected(false, isEditMode: isEditMode)
        }

        // Accessibility
        cell.setAccessibility(label: metadata.fileNameView + ", " + (cell.labelInfo?.text ?? "") + (cell.labelSubinfo?.text ?? ""), value: a11yValues.joined(separator: ", "))

        // Color string find in search
        cell.labelTitle?.textColor = NCBrandColor.shared.textColor
        cell.labelExtension?.textColor = NCBrandColor.shared.textColor

        if isSearchingMode,
           let searchResultStore,
           let title = cell.labelTitle?.text {
            let longestWordRange = (title.lowercased() as NSString).range(of: searchResultStore)
            let attributedString = NSMutableAttributedString(string: title)
            attributedString.setAttributes([NSAttributedString.Key.foregroundColor: UIColor.systemBlue], range: longestWordRange)
            cell.labelTitle?.attributedText = attributedString
        }

        // TAGS
        cell.setTags(tags: Array(metadata.tags))

        // SearchingMode - TAG Separator Hidden
        if isSearchingMode {
            cell.labelInfoSeparator.isHidden = true
        }

        // Hide buttons
        if metadata.name != global.appName {
            cell.setButtonsHidden(true)
        }

        cell.setIconOutlines()

        // Obligatory here, at the end !!
        cell.metadata = metadata

        return cell
    }
}
#endif
