// SPDX-FileCopyrightText: Nextcloud GmbH
// SPDX-FileCopyrightText: 2025 Marino Faggiana
// SPDX-License-Identifier: GPL-3.0-or-later

import UIKit

protocol NCRecommendationsCellDelegate: AnyObject {
    func onMenuIntent(with metadata: tableMetadata?)
    func openContextMenu(with metadata: tableMetadata?, button: UIButton, sender: Any)
}

class NCRecommendationsCell: UICollectionViewCell, UIGestureRecognizerDelegate {
    @IBOutlet weak var image: UIImageView!
    @IBOutlet weak var labelFilename: UILabel!
    @IBOutlet weak var labelExtensionFilename: UILabel!
    @IBOutlet weak var labelInfo: UILabel!
    @IBOutlet weak var buttonMore: UIButton!

    var delegate: NCRecommendationsCellDelegate?
    var recommendedFiles: tableRecommendedFiles = tableRecommendedFiles()

    var metadata: tableMetadata? {
        didSet {
            delegate?.openContextMenu(with: metadata, button: buttonMore, sender: self) /* preconfigure UIMenu with each metadata */
        }
    }

    override func awakeFromNib() {
        super.awakeFromNib()

        let tapObserver = UITapGestureRecognizer(target: self, action: #selector(handleTapObserver(_:)))
        tapObserver.cancelsTouchesInView = false
        tapObserver.delegate = self
        contentView.addGestureRecognizer(tapObserver)

        initCell()
    }

    override func prepareForReuse() {
        super.prepareForReuse()
        initCell()
    }

    func initCell() {
        let imageButton = UIImage(systemName: "ellipsis.circle.fill", withConfiguration: UIImage.SymbolConfiguration(pointSize: 15, weight: .thin))?.applyingSymbolConfiguration(UIImage.SymbolConfiguration(paletteColors: [.black, .white]))

        buttonMore.setImage(imageButton, for: .normal)
        buttonMore.layer.shadowColor = UIColor.black.cgColor
        buttonMore.layer.shadowOpacity = 0.2
        buttonMore.layer.shadowOffset = CGSize(width: 2, height: 2)
        buttonMore.layer.shadowRadius = 4

        image.image = nil
        labelFilename.text = ""
        labelExtensionFilename.text = ""
        labelExtensionFilename.isHidden = true
        labelInfo.text = ""

        //
        // These labels use fonts generated by the custom UIFont helpers defined in
        // the UIFont extension (e.g. `.callout()`, `.caption1()`).
        //
        // Those helpers wrap `UIFontMetrics` to provide Dynamic Type scaling while
        // applying an upper bound to the maximum font size. This ensures:
        //
        // - The text respects the user's preferred accessibility size.
        // - The UI layout remains stable and does not grow indefinitely.
        //
        // `adjustsFontForContentSizeCategory` is enabled to allow UIKit to
        // automatically update the font when the user changes the Dynamic Type
        // setting while the application is running.
        //
        // Without this flag, the label would keep the initially computed font size
        // and would not react to content size category changes.
        //
        // In summary:
        //
        // UIFont helper:
        //     Defines how the font scales and its maximum size.
        //
        // adjustsFontForContentSizeCategory:
        //     Enables live updates when accessibility settings change.
        //
        labelFilename.font = .callout()
        labelFilename.adjustsFontForContentSizeCategory = true

        labelExtensionFilename.font = .footnote()
        labelExtensionFilename.adjustsFontForContentSizeCategory = true

        labelInfo.font = .footnote()
        labelInfo.adjustsFontForContentSizeCategory = true

        buttonMore.menu = nil
        buttonMore.showsMenuAsPrimaryAction = true
        contentView.bringSubviewToFront(buttonMore)
    }

    @objc private func handleTapObserver(_ g: UITapGestureRecognizer) {
        let location = g.location(in: contentView)

        if buttonMore.frame.contains(location) {
            delegate?.onMenuIntent(with: metadata)
        }
    }

    func setImageCorner(withBorder: Bool) {
        image.layer.cornerRadius = 10
        image.layer.masksToBounds = true
        if withBorder {
            image.layer.borderWidth = 0.5
            image.layer.borderColor = UIColor.separator.cgColor
        } else {
            image.layer.borderWidth = 0
            image.layer.borderColor = UIColor.clear.cgColor
        }
    }
}
