source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EARestrictedScrollView', :exclusive => true do
  pod 'EARestrictedScrollView', :path => '../'
end

target 'Tests', :exclusive => true do
    pod 'EARestrictedScrollView', :path => '../'
    
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase/Core'
    pod 'Expecta+Snapshots', :git => 'https://github.com/dblock/ios-snapshot-test-case-expecta.git'
end
