//
//  CCImages.h
//  Crypto Cloud Technology Nextcloud
//
//  Created by Marino Faggiana on 15/06/16.
//  Copyright (c) 2014 TWS. All rights reserved.
//
//  Author Marino Faggiana <m.faggiana@twsweb.it>
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifdef NC

#define image_launchscreen                      @"nextcloudlaunchscreen"
#define image_activeCameraUpload_en             @"activeCameraUploadNextcloud_en"
#define image_activeCameraUpload_it             @"activeCameraUploadNextcloud_it"
#define image_attention                         @"attention"
#define image_audio                             @"audio"
#define image_audiocrypto                       @"audiocrypto"
#define image_bkfull                            @"bkfull"
#define image_bkempty                           @"bkempty"
#define image_brandCameraUpload                 @"nextcloudCameraUpload"
#define image_brandOffline                      @"nextcloudOffline"
#define image_brandLocal                        @"nextcloudLocal"
#define image_brandNavigationController         @"nextcloud_navigationcontroller"
#define image_brandNavigationController1        @"nextcloud_navigationcontroller1"
#define image_brandNavigationController2        @"nextcloud_navigationcontroller2"
#define image_brandNavigationController3        @"nextcloud_navigationcontroller3"
#define image_brandNavigationControllerOffline  @"nextcloud_navigationcontroller_offline"
#define image_brandSfondoiPad                   @"nextcloud_sfondo_iPad"
#define image_checked                           @"checkedNextcloud"
#define image_decryptedSelectedFiles            @"decryptedSelectedFilesNextcloud"
#define image_deleteSelectedFiles               @"deleteSelectedFilesNextcloud"
#define image_downloadSelectedFiles             @"downloadSelectedFilesNextcloud"
#define image_drag                              @"dragNextcloud"
#define image_encryptedSelectedFiles            @"encryptedSelectedFilesNextcloud"
#define image_folderphotocamera                 @"folderphotocameraNextcloud"
#define image_MenuDirectoryOnTop                @"menuDirectoryOnTopNextcloud"
#define image_MenuGroupByAlphabetic             @"MenuGroupByAlphabeticNextcloud"
#define image_MenuGroupByDate                   @"MenuGroupByDateNextcloud"
#define image_MenuGroupByTypeFile               @"MenuGroupByTypeFileNextcloud"
#define image_MenuOrdeyByDate                   @"MenuOrdeyByDateNextcloud"
#define image_MenuOrderByFileName               @"MenuOrderByFileNameNextcloud"
#define image_MenuOrdinamentoDiscendente        @"MenuOrdinamentoDiscendenteNextcloud"
#define image_MenuOrdinamentoAscendente         @"MenuOrdinamentoAscendenteNextcloud"
#define image_moveSelectedFiles                 @"moveSelectedFilesNextcloud"
#define image_quickActionPhotos                 @"quickActionPhotosNextcloud"
#define image_quickActionUploadClear            @"quickActionUploadClearNextcloud"
#define image_quickActionUploadEncrypted        @"quickActionUploadEncryptedNextcloud"
#define image_quickActionUploadOffline          @"quickActionUploadOfflineNextcloud"
#define image_seleziona                         @"selezionaNextcloud"
#define image_saveSelectedFiles                 @"saveSelectedFilesNextcloud"
#define image_settingsMail                      @"settingsMailNextcloud"
#define image_settingsManagePhotos              @"settingsManagePhotosNextcloud"
#define image_settingsManagePhotosChange        @"settingsManagePhotosChangeNextcloud"
#define image_tabBarFile                        @"tabBarNextcloud"
#define image_thumbs                            @"thumbsNextcloud"
#define image_notification                      @"notification"

#endif

#define image_actionSheetRename                 @"renameNextcloud"
#define image_actionSheetMove                   @"moveNextcloud"
#define image_actionSheetCrypto                 @"actionSheetCrypto"
#define image_actionSheetLock                   @"actionSheetLock"
#define image_actionSheetShare                  @"shareNextcloud"
#define image_actionSheetReload                 @"reloadNextcloud"
#define image_actionSheetOpenIn                 @"openInNextcloud"
#define image_actionSheetOffline                @"actionSheetOffline"
#define image_actionSheetLocal                  @"localStorageNextcloud"
#define image_directory                         @"directory"
#define image_directorycriptata                 @"directorycriptata"
#define image_document                          @"document"
#define image_documentcrypto                    @"documentcrypto"
#define image_offline                           @"offline"
#define image_offlinecrypto                     @"offlinecrypto"
#define image_file                              @"file"
#define image_filePreviewDownload               @"filePreviewDownload"
#define image_filePreviewDownloadCrypto         @"filePreviewDownloadCrypto"
#define image_filePreviewError                  @"filePreviewError"
#define image_folder                            @"folder"
#define image_foldercrypto                      @"foldercrypto"
#define image_home                              @"home"
#define image_lock                              @"lock"
#define image_more                              @"more"
#define image_movie                             @"movie"
#define image_moviecrypto                       @"moviecrypto"
#define image_navBarOffline                     @"navBarOffline"
#define image_navBarLocal                       @"navBarLocal"
#define image_openSelectedFiles                 @"openSelectedFiles"
#define image_passcode                          @"passcode"
#define image_pdf                               @"pdf"
#define image_pdfcrypto                         @"pdfcrypto"
#define image_photo                             @"photo"
#define image_photocrypto                       @"photocrypto"
#define image_photosDownload                    @"photosDownload"
#define image_plist                             @"plist"
#define image_reloadtask                        @"reloadtask"
#define image_reloadtaskcrypto                  @"reloadtaskcrypto"
#define image_removetask                        @"removetask"
#define image_removetaskcrypto                  @"removetaskcrypto"
#define image_settings                          @"settings"
#define image_settingsAccountDelete             @"settingsAccountDelete"
#define image_settingsAccountDropbox            @"settingsAccountDropbox"
#define image_settingsAccountModify             @"settingsAccountModify"
#define image_settingsAccountNextcloud          @"settingsAccountNextcloud"
#define image_settingsAccountOwnCloud           @"settingsAccountOwnCloud"
#define image_settingsAcknowledgements          @"settingsAcknowledgements"
#define image_settingsAdmin                     @"settingsAdmin"
#define image_settingsCameraUpload              @"settingsCameraUpload"
#define image_settingsClearCache                @"settingsClearCache"
#define image_settingsCredentials               @"settingsCredentials"
#define image_settingsExit                      @"settingsExit"
#define image_settingsHelp                      @"settingsHelp"
#define image_settingsKeyMail                   @"settingsKeyMail"
#define image_settingsOptimizations             @"settingsOptimizations"
#define image_settingsPasscodeNO                @"settingsPasscodeNO"
#define image_settingsPasscodeYES               @"settingsPasscodeYES"
#define image_settingsSync                      @"settingsSync"
#define image_shareConnect                      @"shareConnect"
#define image_shareExtEncrypt                   @"shareExtEncrypt"
#define image_shareLink                         @"shareLink"
#define image_shareMounted                      @"shareMounted"
#define image_shareUser                         @"shareUser"
#define image_statusdownload                    @"statusdownload"
#define image_statusdownloadcrypto              @"statusdownloadcrypto"
#define image_statuserror                       @"statuserror"
#define image_statusstop                        @"statusstop"
#define image_statusstopcrypto                  @"statusstopcrypto"
#define image_statusupload                      @"statusupload"
#define image_statusuploadcrypto                @"statusuploadcrypto"
#define image_stoptask                          @"stoptask"
#define image_stoptaskcrypto                    @"stoptaskcrypto"
#define image_tabBarOffline                     @"tabBarOffline"
#define image_tabBarLocal                       @"tabBarLocal"
#define image_tabBarPhotos                      @"tabBarPhotos"
#define image_tabBarSettings                    @"tabBarSettings"
#define image_txt                               @"txt"
#define image_txtcrypto                         @"txtcrypto"
#define image_typeCloudDropbox                  @"typeCloudDropbox"
#define image_typeCloudNextcloud                @"typeCloudNextcloud"
#define image_typeCloudOwnCloud                 @"typeCloudOwnCloud"
#define image_typeFileCompress                  @"typeFileCompress"
#define image_filetype_htlm                     @"filetype_html"
#define image_filetype_htlm_crypto              @"filetype_html_crypto"
#define image_uploadchiaro                      @"uploadchiaro"
#define image_uploadcryptato                    @"uploadcryptato"
#define image_uploaddisable                     @"uploaddisable"
#define image_utorrent                          @"utorrent"
#define image_utorrentcrypto                    @"utorrentcrypto"
#define image_WiFiSmall                         @"WiFiSmall"
#define image_xls                               @"xls"
#define image_xlscrypto                         @"xlscrypto"
