// SPDX-FileCopyrightText: Nextcloud GmbH
// SPDX-FileCopyrightText: 2018 Marino Faggiana
// SPDX-License-Identifier: GPL-3.0-or-later

import UIKit
import MarkdownKit
import RealmSwift

class NCSectionFirstHeaderEmptyData: UICollectionReusableView {
    @IBOutlet weak var emptyImage: UIImageView!
    @IBOutlet weak var emptyTitle: UILabel!
    @IBOutlet weak var emptyDescription: UILabel!

    override func awakeFromNib() {
        super.awakeFromNib()
        initHeader()
    }

    override func prepareForReuse() {
        super.prepareForReuse()
        initHeader()
    }

    func initHeader() {
        emptyImage.image = nil
        emptyTitle.text = ""
        emptyDescription.text = ""

        // MARK: - Dynamic Type Font Configuration
        //
        // These labels use fonts generated by the custom UIFont helpers defined in
        // the UIFont extension (e.g. `.callout()`, `.caption1()`).
        //
        // Those helpers wrap `UIFontMetrics` to provide Dynamic Type scaling while
        // applying an upper bound to the maximum font size. This ensures:
        //
        // - The text respects the user's preferred accessibility size.
        // - The UI layout remains stable and does not grow indefinitely.
        //
        // `adjustsFontForContentSizeCategory` is enabled to allow UIKit to
        // automatically update the font when the user changes the Dynamic Type
        // setting while the application is running.
        //
        // Without this flag, the label would keep the initially computed font size
        // and would not react to content size category changes.
        //
        // In summary:
        //
        // UIFont helper:
        //     Defines how the font scales and its maximum size.
        //
        // adjustsFontForContentSizeCategory:
        //     Enables live updates when accessibility settings change.
        //
        emptyTitle.font = .headline()
        emptyTitle.adjustsFontForContentSizeCategory = true

        emptyDescription.font = .caption1()
        emptyDescription.adjustsFontForContentSizeCategory = true
    }

    // MARK: -

    func setContent(emptyImage: UIImage?,
                    emptyTitle: String?,
                    emptyDescription: String?) {
        self.emptyImage.image = emptyImage
        self.emptyTitle.text = emptyTitle
        self.emptyDescription.text = emptyDescription
    }
}
